dist: trusty
sudo: required
services:
  - docker

language: python
cache:
  pip: true
  directories:
    - .mypy_cache

os:
  - linux
install:
  - pip install tox-travis
jobs:
  include:
    - stage: test
      python: "3.7"
      dist: xenial
script: tox
notifications:
  email: false
